
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Tue Jul 01 2025 16:59:25 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Aboutpage2026 extends ContentItem {
    public bannerheading!: Elements.RichTextElement;
    public bannersubheading!: Elements.RichTextElement;
    public bannerdescription!: Elements.RichTextElement;
    public bannervideolink!: Elements.TextElement;
    public featuresbackgroundimage!: Elements.AssetsElement;
    public featuresitems!: Elements.LinkedItemsElement<ContentItem>;
}
