
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Wed Jul 02 2025 13:13:23 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Globalcomponent extends ContentItem {
    public ifacgloballogo!: Elements.AssetsElement;
    public globalmenuitems!: Elements.LinkedItemsElement<ContentItem>;
    public showitems!: Elements.LinkedItemsElement<ContentItem>;
    public address!: Elements.RichTextElement;
    public broughtbytext!: Elements.TextElement;
    public broughtbylogo!: Elements.AssetsElement;
    public ifacdubailogo!: Elements.AssetsElement;
    public dubaimenuitems!: Elements.LinkedItemsElement<ContentItem>;
    public ifacsaudilogo!: Elements.AssetsElement;
    public saudimenuitems!: Elements.LinkedItemsElement<ContentItem>;
    public ifaccariologo!: Elements.AssetsElement;
    public cairomenuitems!: Elements.LinkedItemsElement<ContentItem>;
    public linkedinlink!: Elements.TextElement;
    public tiktoklink!: Elements.TextElement;
    public facebooklink!: Elements.TextElement;
    public youtubelink!: Elements.TextElement;
    public instagramlink!: Elements.TextElement;
}
