
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Sat Jun 28 2025 14:40:57 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Globalcomponent extends ContentItem {
    public ifacgloballogo!: Elements.AssetsElement;
    public globalmenuitems!: Elements.LinkedItemsElement<ContentItem>;
    public showitems!: Elements.LinkedItemsElement<ContentItem>;
    public ifacdubailogo!: Elements.AssetsElement;
    public dubaimenuitems!: Elements.LinkedItemsElement<ContentItem>;
    public ifacsaudilogo!: Elements.AssetsElement;
    public saudimenuitems!: Elements.LinkedItemsElement<ContentItem>;
    public ifaccariologo!: Elements.AssetsElement;
    public cairomenuitems!: Elements.LinkedItemsElement<ContentItem>;
}
