
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Sat Jun 28 2025 14:40:57 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Homepageglobal2026 extends ContentItem {
    public bannerheading!: Elements.TextElement;
    public bannersubheading!: Elements.TextElement;
    public bannervideolink!: Elements.TextElement;
    public ctabutton!: Elements.LinkedItemsElement<ContentItem>;
    public showitemcards!: Elements.LinkedItemsElement<ContentItem>;
    public aboutheading!: Elements.TextElement;
    public aboutsubheading!: Elements.TextElement;
    public aboutcontent!: Elements.RichTextElement;
    public aboutlink!: Elements.TextElement;
    public upcomingheading!: Elements.TextElement;
    public upcomingctaname!: Elements.TextElement;
    public upcomingctalink!: Elements.TextElement;
    public upcomingdate!: Elements.DateTimeElement;
    public galleryheading!: Elements.TextElement;
    public galleryitems!: Elements.AssetsElement;
    public testimonialsheading!: Elements.TextElement;
    public testimonialssubheading!: Elements.TextElement;
    public testimonialsitems!: Elements.LinkedItemsElement<ContentItem>;
    public metadataPagetitle!: Elements.TextElement;
    public metadataMetatitle!: Elements.TextElement;
    public metadataMetadescription!: Elements.TextElement;
    public metadataKeywords!: Elements.TextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'metadata__pagetitle') {
                    return 'metadataPagetitle';
                }
                if (elementName === 'metadata__metatitle') {
                    return 'metadataMetatitle';
                }
                if (elementName === 'metadata__metadescription') {
                    return 'metadataMetadescription';
                }
                if (elementName === 'metadata__keywords') {
                    return 'metadataKeywords';
                }
                return elementName;
            })
        });
    }
}
