
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Sun Jun 29 2025 20:33:16 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Homepagedubai extends ContentItem {
    public bannerheading!: Elements.TextElement;
    public eventlogo!: Elements.AssetsElement;
    public date!: Elements.TextElement;
    public venue!: Elements.TextElement;
    public ctabutton!: Elements.LinkedItemsElement<ContentItem>;
    public statsitems!: Elements.LinkedItemsElement<ContentItem>;
    public aboutheading!: Elements.TextElement;
    public aboutheading2!: Elements.TextElement;
    public aboutcontent!: Elements.RichTextElement;
    public aboutimage!: Elements.AssetsElement;
    public whyexhibitheading1!: Elements.TextElement;
    public whyexhibitheading2!: Elements.TextElement;
    public whyexhibititems!: Elements.LinkedItemsElement<ContentItem>;
    public floorplanheading1!: Elements.TextElement;
    public floorplanheading2!: Elements.TextElement;
    public floorplandescription!: Elements.TextElement;
    public floorplanimage!: Elements.AssetsElement;
    public floorplanctaname!: Elements.TextElement;
    public floorplanctalink!: Elements.TextElement;
    public metadataPagetitle!: Elements.TextElement;
    public metadataMetatitle!: Elements.TextElement;
    public metadataMetadescription!: Elements.TextElement;
    public metadataKeywords!: Elements.TextElement;
    public primarycolor!: Elements.TextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'metadata__pagetitle') {
                    return 'metadataPagetitle';
                }
                if (elementName === 'metadata__metatitle') {
                    return 'metadataMetatitle';
                }
                if (elementName === 'metadata__metadescription') {
                    return 'metadataMetadescription';
                }
                if (elementName === 'metadata__keywords') {
                    return 'metadataKeywords';
                }
                return elementName;
            })
        });
    }
}
