
import { ContentItem, Elements } from '@kentico/kontent-delivery';

/**
 * Generated by '@kentico/kontent-model-generator@3.0.0'
 * Timestamp: Tue Jul 01 2025 19:17:38 GMT+0400 (Gulf Standard Time)
 *
 * Tip: You can replace 'ContentItem' with another generated class to fully leverage strong typing.
 */
export class Visitorpage2026 extends ContentItem {
    public bannerheading!: Elements.RichTextElement;
    public bannersubheading!: Elements.RichTextElement;
    public bannerdescription!: Elements.RichTextElement;
    public bannervideolink!: Elements.TextElement;
    public visitorbenefitheading!: Elements.TextElement;
    public visitorbenefititems!: Elements.LinkedItemsElement<ContentItem>;
    public visitorbenefitsbackground!: Elements.AssetsElement;
    public visitorprofileheading!: Elements.TextElement;
    public visitorprofilesubheading!: Elements.TextElement;
    public visitorprofileitems!: Elements.LinkedItemsElement<ContentItem>;
    public ctabuttonname!: Elements.TextElement;
    public ctabuttonlink!: Elements.TextElement;
    public metadataPagetitle!: Elements.TextElement;
    public metadataMetatitle!: Elements.TextElement;
    public metadataMetadescription!: Elements.TextElement;
    public metadataKeywords!: Elements.TextElement;
    constructor() {
        super({
            propertyResolver: ((elementName: string) => {
                if (elementName === 'metadata__pagetitle') {
                    return 'metadataPagetitle';
                }
                if (elementName === 'metadata__metatitle') {
                    return 'metadataMetatitle';
                }
                if (elementName === 'metadata__metadescription') {
                    return 'metadataMetadescription';
                }
                if (elementName === 'metadata__keywords') {
                    return 'metadataKeywords';
                }
                return elementName;
            })
        });
    }
}
